version: '1'
services:
  dev:
    build: streamlit
    stdin_open: true
    tty: true
    ports:
      - 8501:8501
    volumes:
      - ./streamlit:/opt/dev

  db:
    image: mysql:8.0.27
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060   
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt